export type ConceptDetail = {
    name: string;
    tier: string;
    truth: string;
    timeline: [date: string, text: string][];
    edges: string[];
};

export const CONCEPT_DETAILS: Record<string, ConceptDetail> = {
    transformer: {
        name: 'Transformer Architecture',
        tier: 'TIER 1 · FULL',
        truth: 'Attention-based seq model from "Attention Is All You Need" (2017). Core blocks: <em data-c="attention">self-attention</em> + <em data-c="multi-head">multi-head</em> + FFN + residual + layernorm. Backbone of <em data-c="bert">BERT</em>, <em data-c="gpt">GPT</em>, and modern <em data-c="embedding">embeddings</em>.',
        timeline: [
            ['2026-01-12', 'Seeded from arxiv:1706.03762'],
            ['2026-01-18', 'Karpathy nanoGPT lecture linked'],
            ['2026-02-03', 'Enriched → Tier 1 · 9 sources'],
            ['2026-02-17', 'New edge → flash-attention (0.62)'],
        ],
        edges: ['attention', 'multi-head', 'bert', 'gpt', 'embedding', 'flash-attn', 'scaling'],
    },
    attention: {
        name: 'Self-Attention',
        tier: 'TIER 1 · FULL',
        truth: 'softmax(QKᵀ/√d)V. Every token attends to every other token. O(n²) compute, O(n²) memory. <em data-c="flash-attn">FlashAttention</em> fixes the memory pattern. Underlies every <em data-c="transformer">transformer</em>.',
        timeline: [
            ['2026-01-12', 'From Vaswani et al. 2017'],
            ['2026-01-22', 'Cross-linked to nanoGPT impl'],
            ['2026-02-10', 'Enriched → Tier 1'],
        ],
        edges: ['transformer', 'multi-head', 'qkv', 'softmax', 'flash-attn', 'rope'],
    },
    'multi-head': {
        name: 'Multi-Head Attention',
        tier: 'TIER 2 · ENRICHED',
        truth: 'h parallel <em data-c="attention">attention</em> heads over projected Q/K/V subspaces, concatenated and projected back. Lets the model attend to different relational patterns simultaneously.',
        timeline: [
            ['2026-01-12', 'Defined in "Attention Is All You Need"'],
            ['2026-02-05', 'Enriched → Tier 2'],
        ],
        edges: ['attention', 'transformer', 'qkv', 'bert'],
    },
    bert: {
        name: 'BERT',
        tier: 'TIER 2 · ENRICHED',
        truth: 'Bidirectional encoder. Masked-LM + NSP pretraining. Devlin et al. 2018. SOTA on 11 NLP tasks at release. Built on <em data-c="transformer">transformer</em> encoder stack.',
        timeline: [
            ['2026-01-28', 'From Stanford CS224N lecture'],
            ['2026-02-01', 'Linked to embedding retrieval'],
            ['2026-02-09', 'Enriched → Tier 2'],
        ],
        edges: ['transformer', 'attention', 'multi-head', 'embedding', 'rag'],
    },
    gpt: {
        name: 'GPT',
        tier: 'TIER 2 · ENRICHED',
        truth: 'Decoder-only autoregressive LM. Predicts next token. Scales predictably with compute + params (<em data-c="scaling">scaling laws</em>). Alignment via <em data-c="rlhf">RLHF</em>. Powers modern assistants.',
        timeline: [
            ['2026-01-18', 'Karpathy nanoGPT walkthrough'],
            ['2026-01-25', 'Linked to Kaplan scaling laws'],
            ['2026-02-10', 'Enriched → Tier 2'],
        ],
        edges: ['transformer', 'scaling', 'rlhf', 'dpo', 'rag'],
    },
    embedding: {
        name: 'Embedding',
        tier: 'TIER 2 · ENRICHED',
        truth: 'Dense vector of text/tokens. Enables semantic search and <em data-c="rag">RAG</em>. Cosine or dot-product similarity. Indexed by <em data-c="hnsw">HNSW</em> or IVF.',
        timeline: [
            ['2026-01-20', 'From sentence-transformers repo'],
            ['2026-02-14', 'Enriched → Tier 2'],
        ],
        edges: ['transformer', 'bert', 'rag', 'hnsw', 'rrf', 'bm25'],
    },
    'flash-attn': {
        name: 'Flash Attention',
        tier: 'TIER 3 · STUB',
        truth: 'IO-aware tiled <em data-c="attention">attention</em>. Keeps intermediates in SRAM, avoids materializing the n² matrix. 2–4× speedup, exact (not approximate). Dao et al. 2022.',
        timeline: [['2026-02-17', 'First captured from arxiv:2205.14135']],
        edges: ['attention', 'transformer'],
    },
    scaling: {
        name: 'Scaling Laws',
        tier: 'TIER 2 · ENRICHED',
        truth: 'Loss is a power law in compute / data / params (Kaplan 2020). Chinchilla (Hoffmann 2022) corrected the tokens-to-params ratio: ~20 tokens per param is optimal.',
        timeline: [['2026-01-25', 'From Kaplan + Chinchilla papers']],
        edges: ['transformer', 'gpt', 'chinchilla', 'mlops'],
    },
    rag: {
        name: 'RAG · Retrieval-Augmented Generation',
        tier: 'TIER 1 · FULL',
        truth: 'Retrieve top-k docs with <em data-c="bm25">BM25</em> + <em data-c="embedding">embeddings</em>, fuse via <em data-c="rrf">RRF</em>, condition an LLM on them. Reduces hallucination, grounds answers in cited sources.',
        timeline: [
            ['2026-02-01', 'From Lewis et al. 2020'],
            ['2026-02-20', 'Linked to hybrid search stack'],
            ['2026-03-03', 'Enriched → Tier 1'],
        ],
        edges: ['bm25', 'embedding', 'rrf', 'hnsw', 'agent', 'bert'],
    },
    bm25: {
        name: 'BM25',
        tier: 'TIER 2 · ENRICHED',
        truth: 'Lexical ranker. TF × IDF with length normalization and saturation (k1, b). Strong baseline — often beats vector search on rare terms. Fuses cleanly with <em data-c="embedding">embeddings</em> via <em data-c="rrf">RRF</em>.',
        timeline: [['2026-02-02', 'From Robertson + Zaragoza survey']],
        edges: ['rag', 'rrf', 'embedding'],
    },
    hnsw: {
        name: 'HNSW',
        tier: 'TIER 2 · ENRICHED',
        truth: 'Hierarchical Navigable Small World. Graph-based approximate-NN index. Logarithmic search, incremental inserts. Malkov + Yashunin 2016.',
        timeline: [['2026-02-08', 'From arxiv:1603.09320']],
        edges: ['embedding', 'rag', 'rrf'],
    },
    rrf: {
        name: 'Reciprocal Rank Fusion',
        tier: 'TIER 2 · ENRICHED',
        truth: 'score(d) = Σ 1/(k + rank_i(d)). Simple, parameter-light fusion of multiple ranked lists. Beats learned fusion in many settings.',
        timeline: [['2026-02-15', 'From Cormack et al. SIGIR 2009']],
        edges: ['bm25', 'embedding', 'rag', 'hnsw'],
    },
    pagerank: {
        name: 'PageRank',
        tier: 'TIER 2 · ENRICHED',
        truth: 'Stationary distribution of a random walk on the link graph. PR(u) = (1-d)/N + d · Σ PR(v)/out(v). Damping d=0.85. Brin + Page 1998.',
        timeline: [['2026-02-22', 'Seeded from Stanford CS224W']],
        edges: ['random-walk', 'rag', 'rrf'],
    },
    'random-walk': {
        name: 'Random Walk',
        tier: 'TIER 3 · STUB',
        truth: 'Markov chain over nodes of a graph. Biased walks → node2vec embeddings. Walks with restart → personalized <em data-c="pagerank">PageRank</em>.',
        timeline: [['2026-02-22', 'From node2vec paper']],
        edges: ['pagerank'],
    },
    'sys-design': {
        name: 'System Design',
        tier: 'TIER 1 · FULL',
        truth: 'Trade-offs across <em data-c="cap">consistency</em>, availability, partitioning, latency, cost. Know your read/write ratio. Cache what is cheap to rebuild.',
        timeline: [['2026-01-10', 'From DDIA + Grokking']],
        edges: ['cap', 'raft', 'sharding', 'kafka', 'sqlite', 'cache'],
    },
    cap: {
        name: 'CAP Theorem',
        tier: 'TIER 2 · ENRICHED',
        truth: 'Under network partition, a distributed system chooses consistency OR availability. PACELC refines: without a partition, trade latency vs consistency.',
        timeline: [['2026-01-15', 'Brewer 2000, Gilbert+Lynch 2002']],
        edges: ['sys-design', 'raft', 'sharding'],
    },
    raft: {
        name: 'Raft Consensus',
        tier: 'TIER 2 · ENRICHED',
        truth: 'Understandable consensus. Strong leader, log replication, election timeouts. Safety: committed entries never overwritten. Ongaro + Ousterhout 2014.',
        timeline: [['2026-01-20', 'From raft.github.io + paper']],
        edges: ['sys-design', 'cap', 'sharding'],
    },
    sharding: {
        name: 'Sharding',
        tier: 'TIER 2 · ENRICHED',
        truth: 'Partition data by hash or range across nodes. Consistent hashing minimizes movement on resize. Rebalancing + hot keys are the hard parts.',
        timeline: [['2026-01-24', 'From DDIA ch. 6']],
        edges: ['sys-design', 'cap', 'raft', 'sqlite', 'kafka'],
    },
    kafka: {
        name: 'Kafka',
        tier: 'TIER 3 · STUB',
        truth: 'Append-only distributed log. Partitioned, replicated, replayable. At-least-once by default; exactly-once with idempotent producer + transactions.',
        timeline: [['2026-01-27', 'From Confluent docs']],
        edges: ['sys-design', 'sharding'],
    },
    sqlite: {
        name: 'SQLite',
        tier: 'TIER 3 · STUB',
        truth: 'Single-file embedded SQL DB. WAL, page cache, B-tree. Runs anywhere your process runs — phones, edge, browsers (sqlite-wasm).',
        timeline: [['2026-01-28', 'From sqlite.org internals docs']],
        edges: ['sys-design', 'sharding', 'raft'],
    },
    cache: {
        name: 'Caching',
        tier: 'TIER 3 · STUB',
        truth: 'LRU / LFU / TTL. Cache stampedes → request coalescing + jittered TTLs. Invalidation is the hard problem.',
        timeline: [['2026-01-30', 'From high-scalability notes']],
        edges: ['sys-design'],
    },
    mlops: {
        name: 'MLOps',
        tier: 'TIER 2 · ENRICHED',
        truth: 'Reproducible training → eval → deploy → monitor. Data versioning (DVC), model registry, shadow traffic, canary rollouts, drift detection.',
        timeline: [['2026-02-12', 'From MLOps community stack map']],
        edges: ['fine-tune', 'lora', 'rlhf', 'eval-harness', 'scaling', 'sys-design'],
    },
    'fine-tune': {
        name: 'Fine-Tuning',
        tier: 'TIER 3 · STUB',
        truth: 'Continue training a pretrained LM on a domain corpus or task. Full fine-tune vs parameter-efficient (<em data-c="lora">LoRA</em>, prefix-tuning).',
        timeline: [['2026-02-13', 'From HuggingFace guides']],
        edges: ['mlops', 'lora', 'rlhf'],
    },
    lora: {
        name: 'LoRA',
        tier: 'TIER 3 · STUB',
        truth: 'Low-Rank Adaptation. Freeze base weights, learn ΔW = BA with rank r ≪ d. 10,000× fewer trainable params, no inference overhead when merged.',
        timeline: [['2026-02-13', 'From Hu et al. 2021']],
        edges: ['fine-tune', 'mlops'],
    },
    rlhf: {
        name: 'RLHF',
        tier: 'TIER 3 · STUB',
        truth: 'Reward model from human preferences → PPO fine-tune. <em data-c="dpo">DPO</em> (Rafailov 2023) skips the RL step with a closed-form loss.',
        timeline: [['2026-02-14', 'From InstructGPT paper']],
        edges: ['gpt', 'mlops', 'dpo', 'fine-tune'],
    },
    dpo: {
        name: 'DPO',
        tier: 'TIER 3 · STUB',
        truth: 'Direct Preference Optimization. Reparameterizes RLHF as a simple classification loss on preference pairs. No reward model, no PPO.',
        timeline: [['2026-02-16', 'From arxiv:2305.18290']],
        edges: ['rlhf', 'gpt', 'fine-tune'],
    },
    'eval-harness': {
        name: 'Eval Harness',
        tier: 'TIER 3 · STUB',
        truth: 'Regression suite for LLMs. Task packs (MMLU, HumanEval), graders (exact, LLM-as-judge), versioned prompts, run metadata.',
        timeline: [['2026-02-18', 'From lm-evaluation-harness repo']],
        edges: ['mlops', 'agent'],
    },
    agent: {
        name: 'Agent Loop',
        tier: 'TIER 2 · ENRICHED',
        truth: 'plan → act → observe → repeat. Tools + scratchpad + termination condition. ReAct / toolformer variants. Often calls <em data-c="rag">RAG</em> as a tool.',
        timeline: [['2026-02-25', 'From ReAct paper + anthropic tool-use guide']],
        edges: ['rag', 'mlops', 'eval-harness'],
    },
    chinchilla: {
        name: 'Chinchilla',
        tier: 'TIER 3 · STUB',
        truth: 'Hoffmann et al. 2022. Revised scaling laws: compute-optimal LMs train on ~20 tokens per parameter. Implied most pre-Chinchilla LMs were undertrained.',
        timeline: [['2026-01-26', 'From arxiv:2203.15556']],
        edges: ['scaling', 'gpt'],
    },
    rope: {
        name: 'RoPE',
        tier: 'TIER 3 · STUB',
        truth: 'Rotary Position Embedding. Encodes relative position by rotating Q/K in 2D subspaces. Extrapolates better than learned absolute PEs.',
        timeline: [['2026-02-04', 'From Su et al. 2021']],
        edges: ['attention', 'transformer'],
    },
    qkv: {
        name: 'QKV Projection',
        tier: 'TIER 3 · STUB',
        truth: 'Linear projections W_q, W_k, W_v map input to queries / keys / values for <em data-c="attention">attention</em>. Separate per head in multi-head.',
        timeline: [['2026-01-12', 'From transformer paper']],
        edges: ['attention', 'multi-head', 'transformer'],
    },
    softmax: {
        name: 'Softmax',
        tier: 'TIER 3 · STUB',
        truth: 'exp(x_i) / Σ exp(x_j). Turns logits into a distribution. Numerically stable impl subtracts max first. Used in attention + classification.',
        timeline: [['2026-01-12', 'Standard DL primitive']],
        edges: ['attention'],
    },
    layernorm: {
        name: 'LayerNorm',
        tier: 'TIER 3 · STUB',
        truth: 'Normalize across features within a token. Pre-norm transformers (norm before sublayer) train more stably than post-norm.',
        timeline: [['2026-01-14', 'Ba et al. 2016']],
        edges: ['transformer', 'bert'],
    },
    sgd: {
        name: 'AdamW',
        tier: 'TIER 3 · STUB',
        truth: 'Adam with decoupled weight decay (Loshchilov + Hutter). Default optimizer for transformers. Betas ≈ (0.9, 0.95) for large LMs.',
        timeline: [['2026-02-01', 'From optimizer survey']],
        edges: ['transformer', 'mlops'],
    },
};
