export type Cluster = 'ml' | 'retrieval' | 'systems' | 'mlops';
export type Tier = 1 | 2 | 3;

export type Concept = {
    id: string;
    x: number;
    y: number;
    r: number;
    tier: Tier;
    cluster: Cluster;
    label: string;
    truth: string;
};

export type Edge = [from: string, to: string, weight: number];

export const HERO_CONCEPTS: readonly Concept[] = [
    {
        id: 'transformer',
        x: 200,
        y: 200,
        r: 22,
        tier: 1,
        cluster: 'ml',
        label: 'transformer',
        truth: 'Attention-based seq model. Replaced RNN/LSTM for nearly all sequence tasks.',
    },
    {
        id: 'attention',
        x: 110,
        y: 140,
        r: 18,
        tier: 1,
        cluster: 'ml',
        label: 'self-attention',
        truth: 'softmax(QKᵀ/√d)V. Lets every token look at every other token in one step.',
    },
    {
        id: 'multi-head',
        x: 260,
        y: 110,
        r: 14,
        tier: 2,
        cluster: 'ml',
        label: 'multi-head',
        truth: 'h parallel attention heads over projected subspaces, concatenated + projected.',
    },
    {
        id: 'bert',
        x: 290,
        y: 240,
        r: 16,
        tier: 2,
        cluster: 'ml',
        label: 'bert',
        truth: 'Bidirectional encoder, masked-LM pretraining. Devlin et al. 2018.',
    },
    {
        id: 'gpt',
        x: 180,
        y: 290,
        r: 12,
        tier: 3,
        cluster: 'ml',
        label: 'gpt',
        truth: 'Decoder-only, autoregressive next-token prediction. Scales with compute (Kaplan).',
    },
    {
        id: 'flash-attn',
        x: 70,
        y: 230,
        r: 10,
        tier: 3,
        cluster: 'ml',
        label: 'flash-attention',
        truth: 'IO-aware tiled attention. 2–4× faster, exact, SRAM-friendly.',
    },
    {
        id: 'rope',
        x: 60,
        y: 90,
        r: 11,
        tier: 3,
        cluster: 'ml',
        label: 'rope',
        truth: 'Rotary position embeddings. Encodes relative position via rotation of Q/K.',
    },
    {
        id: 'embedding',
        x: 330,
        y: 320,
        r: 12,
        tier: 2,
        cluster: 'ml',
        label: 'embedding',
        truth: 'Dense vector representation of text/tokens. Powers vector search + RAG.',
    },
    {
        id: 'rag',
        x: 140,
        y: 400,
        r: 16,
        tier: 2,
        cluster: 'retrieval',
        label: 'rag',
        truth: 'Retrieval-Augmented Generation. Retrieve docs → condition LLM on them.',
    },
    {
        id: 'bm25',
        x: 50,
        y: 440,
        r: 12,
        tier: 3,
        cluster: 'retrieval',
        label: 'bm25',
        truth: 'Lexical ranking: TF × IDF with length normalization. Strong baseline.',
    },
    {
        id: 'hnsw',
        x: 60,
        y: 360,
        r: 11,
        tier: 3,
        cluster: 'retrieval',
        label: 'hnsw',
        truth: 'Hierarchical Navigable Small World. Graph-based ANN index, log-scale search.',
    },
    {
        id: 'rrf',
        x: 240,
        y: 420,
        r: 14,
        tier: 2,
        cluster: 'retrieval',
        label: 'rrf-fusion',
        truth: 'Reciprocal Rank Fusion: 1/(k+rank). Fuses lexical + vector rankings simply.',
    },
    {
        id: 'pagerank',
        x: 220,
        y: 470,
        r: 10,
        tier: 3,
        cluster: 'retrieval',
        label: 'pagerank',
        truth: 'Stationary distribution of a random walk over the link graph. Damping 0.85.',
    },
    {
        id: 'random-walk',
        x: 60,
        y: 290,
        r: 9,
        tier: 3,
        cluster: 'retrieval',
        label: 'random-walk',
        truth: 'Markov chain over nodes; biased walks give node2vec-style embeddings.',
    },
    {
        id: 'sys-design',
        x: 500,
        y: 200,
        r: 18,
        tier: 1,
        cluster: 'systems',
        label: 'system-design',
        truth: 'Trade-offs around consistency, availability, partitioning, latency, cost.',
    },
    {
        id: 'raft',
        x: 560,
        y: 130,
        r: 12,
        tier: 2,
        cluster: 'systems',
        label: 'raft',
        truth: 'Understandable consensus: leader election, log replication, safety invariants.',
    },
    {
        id: 'cap',
        x: 420,
        y: 140,
        r: 14,
        tier: 2,
        cluster: 'systems',
        label: 'cap-theorem',
        truth: 'Under partition, pick consistency or availability. No system gets all three.',
    },
    {
        id: 'sharding',
        x: 560,
        y: 260,
        r: 14,
        tier: 2,
        cluster: 'systems',
        label: 'sharding',
        truth: 'Partition data by hash/range across nodes. Rebalancing is the hard part.',
    },
    {
        id: 'kafka',
        x: 470,
        y: 300,
        r: 11,
        tier: 3,
        cluster: 'systems',
        label: 'kafka',
        truth: 'Append-only log broker. Replayable, partitioned, at-least-once by default.',
    },
    {
        id: 'sqlite',
        x: 580,
        y: 340,
        r: 10,
        tier: 3,
        cluster: 'systems',
        label: 'sqlite',
        truth: 'Single-file embedded SQL DB. WAL + page cache. Runs where you run.',
    },
    {
        id: 'cache',
        x: 380,
        y: 70,
        r: 11,
        tier: 3,
        cluster: 'systems',
        label: 'caching',
        truth: 'LRU / LFU. Invalidation is famously the hard problem.',
    },
    {
        id: 'mlops',
        x: 460,
        y: 430,
        r: 14,
        tier: 2,
        cluster: 'mlops',
        label: 'mlops',
        truth: 'Reproducible training + eval + deploy. Data versioning, model registry, shadow eval.',
    },
    {
        id: 'fine-tune',
        x: 540,
        y: 460,
        r: 11,
        tier: 3,
        cluster: 'mlops',
        label: 'fine-tuning',
        truth: 'Continue training on a domain corpus. LoRA keeps params tiny.',
    },
    {
        id: 'lora',
        x: 380,
        y: 460,
        r: 10,
        tier: 3,
        cluster: 'mlops',
        label: 'lora',
        truth: 'Low-rank adapters. Δ = BA, rank r ≪ d. Freeze base weights.',
    },
    {
        id: 'rlhf',
        x: 510,
        y: 380,
        r: 9,
        tier: 3,
        cluster: 'mlops',
        label: 'rlhf',
        truth: 'Reward model from prefs → PPO fine-tune. DPO is the simpler replacement.',
    },
    {
        id: 'eval-harness',
        x: 360,
        y: 380,
        r: 10,
        tier: 3,
        cluster: 'mlops',
        label: 'eval-harness',
        truth: 'Regression suite for LLMs. Task packs, graders, versioned prompts.',
    },
    {
        id: 'agent',
        x: 420,
        y: 230,
        r: 9,
        tier: 3,
        cluster: 'mlops',
        label: 'agent-loop',
        truth: 'plan → act → observe. Tools + scratchpad + termination condition.',
    },
    {
        id: 'scaling-laws',
        x: 320,
        y: 170,
        r: 11,
        tier: 2,
        cluster: 'mlops',
        label: 'scaling-laws',
        truth: 'Loss is a power law in compute / data / params. Chinchilla-optimal ratios.',
    },
];

export const HERO_EDGES: readonly Edge[] = [
    ['transformer', 'attention', 0.95],
    ['transformer', 'multi-head', 0.85],
    ['transformer', 'bert', 0.9],
    ['transformer', 'gpt', 0.3],
    ['attention', 'flash-attn', 0.6],
    ['attention', 'multi-head', 0.8],
    ['multi-head', 'bert', 0.7],
    ['bert', 'embedding', 0.55],
    ['gpt', 'rope', 0.3],
    ['rag', 'bm25', 0.8],
    ['rag', 'hnsw', 0.8],
    ['rag', 'rrf', 0.9],
    ['rrf', 'pagerank', 0.5],
    ['bm25', 'random-walk', 0.35],
    ['sys-design', 'raft', 0.95],
    ['sys-design', 'cap', 0.85],
    ['sys-design', 'sharding', 0.75],
    ['sharding', 'kafka', 0.4],
    ['sharding', 'sqlite', 0.6],
    ['cap', 'sqlite', 0.5],
    ['mlops', 'fine-tune', 0.7],
    ['mlops', 'lora', 0.5],
    ['mlops', 'rlhf', 0.45],
    ['eval-harness', 'agent', 0.7],
    ['rrf', 'transformer', 0.65],
    ['scaling-laws', 'transformer', 0.85],
    ['scaling-laws', 'gpt', 0.8],
    ['scaling-laws', 'mlops', 0.75],
    ['rag', 'embedding', 0.6],
    ['agent', 'rag', 0.3],
    ['mlops', 'sys-design', 0.55],
    ['raft', 'sqlite', 0.5],
    ['bm25', 'sys-design', 0.4],
    ['lora', 'fine-tune', 0.35],
    ['pagerank', 'random-walk', 0.4],
];

export const CLUSTER_COLORS: Record<Cluster, string> = {
    ml: '#c8501f',
    retrieval: '#0ea5e9',
    systems: '#3b5bdb',
    mlops: '#64748b',
};

export type MiniNode = {
    id: string;
    x: number;
    y: number;
    r: number;
    tier: Tier;
    label: string;
};

export const MINI_NODES: readonly MiniNode[] = [
    { id: 'transformer', x: 300, y: 260, r: 32, tier: 1, label: 'transformer' },
    { id: 'attention', x: 140, y: 170, r: 22, tier: 1, label: 'self-attention' },
    { id: 'multi-head', x: 470, y: 160, r: 18, tier: 2, label: 'multi-head' },
    { id: 'bert', x: 490, y: 260, r: 15, tier: 2, label: 'bert' },
    { id: 'gpt', x: 440, y: 380, r: 17, tier: 2, label: 'gpt' },
    { id: 'embedding', x: 200, y: 420, r: 16, tier: 2, label: 'embedding' },
    { id: 'flash-attn', x: 350, y: 450, r: 13, tier: 3, label: 'flash-attn' },
    { id: 'scaling', x: 110, y: 310, r: 14, tier: 2, label: 'scaling-laws' },
    { id: 'rope', x: 55, y: 210, r: 11, tier: 3, label: 'rope' },
    { id: 'qkv', x: 50, y: 110, r: 10, tier: 3, label: 'qkv-proj' },
    { id: 'softmax', x: 220, y: 60, r: 11, tier: 3, label: 'softmax' },
    { id: 'layernorm', x: 340, y: 90, r: 13, tier: 3, label: 'layernorm' },
    { id: 'rag', x: 560, y: 110, r: 14, tier: 2, label: 'rag' },
    { id: 'rlhf', x: 540, y: 450, r: 10, tier: 3, label: 'rlhf' },
    { id: 'dpo', x: 470, y: 480, r: 9, tier: 3, label: 'dpo' },
    { id: 'rrf', x: 240, y: 490, r: 11, tier: 3, label: 'rrf-fusion' },
    { id: 'hnsw', x: 110, y: 470, r: 10, tier: 3, label: 'hnsw' },
    { id: 'bm25', x: 400, y: 520, r: 9, tier: 3, label: 'bm25' },
    { id: 'chinchilla', x: 50, y: 370, r: 9, tier: 3, label: 'chinchilla' },
    { id: 'mlops', x: 60, y: 430, r: 11, tier: 2, label: 'mlops' },
    { id: 'agent', x: 300, y: 540, r: 11, tier: 2, label: 'agent-loop' },
    { id: 'sgd', x: 560, y: 320, r: 10, tier: 3, label: 'adamw' },
];

export const MINI_EDGES: readonly Edge[] = [
    ['transformer', 'attention', 1],
    ['transformer', 'multi-head', 0.85],
    ['transformer', 'bert', 0.7],
    ['transformer', 'gpt', 0.8],
    ['transformer', 'embedding', 0.75],
    ['transformer', 'flash-attn', 0.5],
    ['transformer', 'scaling', 0.7],
    ['attention', 'rope', 0.3],
    ['attention', 'qkv', 0.7],
    ['attention', 'softmax', 0.6],
    ['attention', 'layernorm', 0.45],
    ['attention', 'flash-attn', 0.7],
    ['multi-head', 'rag', 0.4],
    ['multi-head', 'qkv', 0.6],
    ['multi-head', 'bert', 0.6],
    ['bert', 'layernorm', 0.4],
    ['gpt', 'rlhf', 0.8],
    ['gpt', 'dpo', 0.6],
    ['gpt', 'rag', 0.3],
    ['embedding', 'rrf', 0.85],
    ['embedding', 'hnsw', 0.75],
    ['embedding', 'bm25', 0.35],
    ['flash-attn', 'sgd', 0.3],
    ['scaling', 'chinchilla', 0.85],
    ['scaling', 'mlops', 0.55],
    ['scaling', 'gpt', 0.55],
    ['mlops', 'agent', 0.4],
    ['agent', 'rag', 0.6],
    ['rag', 'bm25', 0.7],
    ['rag', 'rrf', 0.7],
    ['rrf', 'hnsw', 0.5],
    ['rlhf', 'dpo', 0.6],
    ['bert', 'rag', 0.3],
];
